# -*- coding: utf-8 -*-
"""Game1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Mze3Wvxwkr20-vTEk2yLA86-57pakBB
"""

import random
# snake water gun is same as stone paper scissors
def gameWin(comp,you):
  if comp == you :
    return None
  elif comp == 's':
    if you == 'w':
      return False
    elif you == "g":
      return True

  elif comp == 'w':
    if you == 'g':
      return False
    elif you == "s":
      return True
  elif comp == 'g':
      if you == 's':
        return False
      elif you == "w":
        return True
print("Computer Turn: Snake(s) Water(w) or Gun(g)")
randNo = random.randint(1,3)
if randNo == 1:
  comp ="s"
elif randNo == 2:
  comp ="w"
elif randNo == 2:
  comp ="g"

you = input("Player 2 Turn : Snake(s) Water(w) or Gun(g)")
print(f"Computer chose  {comp}")
print(f"your chose  {you}")
a = gameWin(comp, you)
if a == None:
  print("The Game is tie")
elif a:
  print("You Win the Game")
else :
  print("You lose the Game")

